

services:
  web:
    build: .
    container_name: wagtail_django
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_wagtail
    restart: always
    environment:
      POSTGRES_DB: wagtail_db
      POSTGRES_USER: wagtail_user
      POSTGRES_PASSWORD: wagtail_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
