# Generated by Django 5.1.4 on 2025-06-01 21:29

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import immobilier.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text='Classe Font Awesome, ex: fa-home', max_length=50)),
            ],
            options={
                'verbose_name': 'type de bien',
                'verbose_name_plural': 'types de biens',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='particulier', max_length=15, verbose_name="Type d'utilisateur")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
            managers=[
                ('objects', immobilier.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('particulier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_particulier', to=settings.AUTH_USER_MODEL, verbose_name='Particulier')),
                ('professionnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_pro', to=settings.AUTH_USER_MODEL, verbose_name='Professionnel')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False, verbose_name='Message lu')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='immobilier.conversation', verbose_name='Conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProfilProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entreprise', models.CharField(choices=[('agence', 'Agence immobilière'), ('promoteur', 'Promoteur immobilier'), ('constructeur', 'Constructeur'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Type d'entreprise")),
                ('nom_entreprise', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('siret', models.CharField(blank=True, help_text='14 chiffres, sans espace', max_length=14, verbose_name='Numéro SIRET')),
                ('description', models.TextField(blank=True, verbose_name="Description de l'activité")),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone professionnel')),
                ('annee_creation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)], verbose_name='Année de création')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse du siège social')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='professionnels/logos/', verbose_name='Logo')),
                ('cgu_acceptees', models.BooleanField(default=False, verbose_name="J'accepte les conditions générales d'utilisation")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('nombre_avis', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_pro', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'profil professionnel',
                'verbose_name_plural': 'profils professionnels',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('kbis', 'KBIS'), ('assurance', "Attestation d'assurance"), ('autre', 'Autre document')], max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='professionnels/documents/', verbose_name='Fichier')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('est_verifie', models.BooleanField(default=False, verbose_name='Document vérifié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='immobilier.profilprofessionnel', verbose_name='Professionnel')),
            ],
            options={
                'verbose_name': 'document professionnel',
                'verbose_name_plural': 'documents professionnels',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProjetImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('location', 'Location')], max_length=20, verbose_name='Type de projet')),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('local', 'Local commercial'), ('terrain', 'Terrain'), ('autre', 'Autre')], max_length=20, verbose_name='Type de bien recherché')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget (€)')),
                ('surface_min', models.PositiveIntegerField(verbose_name='Surface minimale (m²)')),
                ('surface_max', models.PositiveIntegerField(verbose_name='Surface maximale (m²)')),
                ('localisation', models.CharField(max_length=255, verbose_name='Localisation recherchée')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'projet immobilier',
                'verbose_name_plural': 'projets immobiliers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='immobilier.projetimmobilier', verbose_name='Projet concerné'),
        ),
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_transaction', models.CharField(choices=[('vente', 'À vendre'), ('location', 'À louer')], max_length=10, verbose_name='Type de transaction')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (€)')),
                ('surface', models.PositiveIntegerField(help_text='Surface en m²', verbose_name='Surface')),
                ('nombre_pieces', models.PositiveIntegerField(verbose_name='Nombre de pièces')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='biens/', verbose_name='Image principale')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobilier.typebien', verbose_name='Type de bien')),
            ],
            options={
                'verbose_name': 'bien immobilier',
                'verbose_name_plural': 'biens immobiliers',
                'ordering': ['-date_creation'],
                'permissions': [('publish_bien', 'Peut publier un bien'), ('unpublish_bien', 'Peut retirer un bien de la publication')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('projet', 'professionnel', 'particulier')},
        ),
    ]
