# Generated by Django 4.2.7 on 2025-06-02 01:19

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilprofessionnel',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[MinValueValidator(0), MaxValueValidator(5)], verbose_name='Note moyenne'),
        ),
    ]
