# Generated by Django 4.2.7 on 2025-06-02 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_add_note_moyenne_to_profilprofessionnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('civilite', models.CharField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], max_length=10, verbose_name='Civilité')),
                ('situation_familiale', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('pacs', 'Pacsé(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='Situation familiale')),
                ('nombre_enfants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('revenu_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenu mensuel (€)')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Recevoir les notifications par email')),
                ('notification_sms', models.BooleanField(default=False, verbose_name='Recevoir les notifications par SMS')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_particulier', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'profil particulier',
                'verbose_name_plural': 'profils particuliers',
                'ordering': ['-date_creation'],
            },
        ),
    ]
