# Generated by Django 4.2.7 on 2025-06-02 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0004_profilparticulier'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetimmobilier',
            name='professionnel_selectionne',
            field=models.ForeignKey(blank=True, help_text='Professionnel qui a été choisi pour ce projet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_selectionnes', to=settings.AUTH_USER_MODEL, verbose_name='Professionnel sélectionné'),
        ),
    ]
