# Generated by Django 4.2.7 on 2025-06-02 03:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0005_projetimmobilier_professionnel_selectionne'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du type de professionnel')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text='Classe Font Awesome, ex: fa-user-tie', max_length=50)),
            ],
            options={
                'verbose_name': 'type de professionnel',
                'verbose_name_plural': 'types de professionnels',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EtapeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etape', models.CharField(choices=[('definition', 'Définition du projet'), ('recherche', 'Recherche de biens'), ('visites', 'Visites'), ('offres', 'Offres et négociations'), ('compromis', 'Signature du compromis'), ('pret', 'Obtention du prêt'), ('acte', "Signature de l'acte définitif"), ('remise_cles', 'Remise des clés'), ('estimation', 'Estimation du bien'), ('diagnostics', 'Réalisation des diagnostics'), ('valorisation', 'Valorisation du bien'), ('commercialisation', 'Commercialisation'), ('visites_vente', 'Organisation des visites'), ('compromis_vente', 'Signature du compromis'), ('acte_vente', "Signature de l'acte de vente"), ('suivi_apres_vente', 'Suivi après-vente')], max_length=20, verbose_name="Type d'étape")),
                ('type_projet', models.CharField(max_length=10, verbose_name='Type de projet')),
                ('ordre', models.PositiveIntegerField(verbose_name="Ordre d'affichage")),
                ('titre', models.CharField(max_length=100, verbose_name="Titre de l'étape")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_obligatoire', models.BooleanField(default=True, verbose_name='Étape obligatoire')),
                ('professionnels_associes', models.ManyToManyField(blank=True, related_name='etapes', to='immobilier.typeprofessionnel', verbose_name='Types de professionnels associés')),
            ],
            options={
                'verbose_name': 'étape de projet',
                'verbose_name_plural': 'étapes de projet',
                'ordering': ['type_projet', 'ordre'],
                'unique_together': {('type_etape', 'type_projet')},
            },
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='etape_actuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_actuels', to='immobilier.etapeprojet', verbose_name='Étape actuelle'),
        ),
        migrations.CreateModel(
            name='EtapeProjetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_terminee', models.BooleanField(default=False, verbose_name='Étape terminée')),
                ('notes', models.TextField(blank=True, verbose_name="Notes sur l'étape")),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='immobilier.etapeprojet', verbose_name='Étape')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_instance', to='immobilier.projetimmobilier', verbose_name='Projet')),
            ],
            options={
                'verbose_name': "instance d'étape de projet",
                'verbose_name_plural': "instances d'étapes de projet",
                'ordering': ['projet', 'etape__ordre'],
                'unique_together': {('projet', 'etape')},
            },
        ),
    ]
