# Generated by Django 4.2.7 on 2025-06-02 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0006_typeprofessionnel_etapeprojet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapeprojetinstance',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date de début'),
        ),
    ]
