# Generated by Django 4.2.7 on 2025-06-02 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0007_make_date_debut_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapeprojetinstance',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
    ]
