# Generated by Django 4.2.7 on 2025-06-02 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0008_alter_etapeprojetinstance_date_debut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetimmobilier',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='projetimmobilier',
            name='localisation',
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='avec_exterieur',
            field=models.BooleanField(default=False, verbose_name='Avec extérieur'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='avec_garage',
            field=models.BooleanField(default=False, verbose_name='Avec garage'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget maximum (€)'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget minimum (€)'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='caracteristiques',
            field=models.TextField(blank=True, help_text='Jardin, balcon, garage, etc.', verbose_name='Caractéristiques du bien'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='date_achat',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='exposition',
            field=models.CharField(blank=True, help_text='Exposition du jardin ou du séjour', max_length=100, verbose_name='Exposition'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='nombre_pieces',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pièces'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='proximite_transports',
            field=models.TextField(blank=True, help_text='Tram, métro, bus, gares à proximité', verbose_name='Proximité des transports'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='secteur_geographique',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Secteur géographique'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='surface',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface (m²)'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='surface_exterieur',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface extérieure (m²)'),
        ),
        migrations.AddField(
            model_name='projetimmobilier',
            name='travaux_envisages',
            field=models.CharField(blank=True, choices=[('amenagement', 'Aménagement'), ('deco', 'Décoration'), ('renovation_legere', 'Petite rénovation'), ('renovation_complete', 'Rénovation complète')], max_length=20, null=True, verbose_name='Travaux envisagés'),
        ),
        migrations.AlterField(
            model_name='projetimmobilier',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description complémentaire'),
        ),
        migrations.AlterField(
            model_name='projetimmobilier',
            name='surface_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface maximale (m²)'),
        ),
        migrations.AlterField(
            model_name='projetimmobilier',
            name='surface_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface minimale (m²)'),
        ),
        migrations.AlterField(
            model_name='projetimmobilier',
            name='type_bien',
            field=models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('immeuble', 'Immeuble'), ('local_commercial', 'Local commercial'), ('terrain', 'Terrain'), ('autre', 'Autre')], max_length=20, verbose_name='Type de bien'),
        ),
        migrations.AlterField(
            model_name='projetimmobilier',
            name='type_projet',
            field=models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente')], max_length=20, verbose_name='Type de projet'),
        ),
    ]
