# Generated by Django 4.2.7 on 2025-06-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0009_remove_projetimmobilier_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilprofessionnel',
            name='etapes_projet',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez les étapes de projet pour lesquelles vous proposez vos services', related_name='professionnels', to='immobilier.etapeprojet', verbose_name='Étapes de projet prises en charge'),
        ),
    ]
