# Generated by Django 4.2.7 on 2025-06-02 05:13

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Récupération du modèle historique
    ProjetImmobilier = apps.get_model('immobilier', 'ProjetImmobilier')
    
    # Mise à jour des anciens champs vers les nouveaux
    for projet in ProjetImmobilier.objects.all():
        # Si le projet a un budget défini, le convertir en budget_min et budget_max
        if hasattr(projet, 'budget') and projet.budget is not None:
            if projet.budget_min is None:
                projet.budget_min = projet.budget
            if projet.budget_max is None:
                projet.budget_max = projet.budget
        
        # Si le projet a une localisation, la copier dans secteur_geographique
        if hasattr(projet, 'localisation') and projet.localisation and not projet.secteur_geographique:
            projet.secteur_geographique = projet.localisation
            
        projet.save()

def reverse_func(apps, schema_editor):
    # Cette fonction est vide car nous ne pouvons pas restaurer les anciennes valeurs
    # une fois que les champs ont été supprimés
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0010_profilprofessionnel_etapes_projet'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
