# Generated by Django 5.1.6 on 2025-02-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carte_dashboard_projet_carte_projets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='cartes',
        ),
        migrations.AddField(
            model_name='projet',
            name='metier',
            field=models.CharField(choices=[('infirmier', 'Infirmier'), ('policier', 'Policier'), ('enseignant', 'Enseignant'), ('ingenieur', 'Ingénieur'), ('medecin', 'Médecin'), ('artiste', 'Artiste'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projet',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.particulier'),
        ),
        migrations.DeleteModel(
            name='Carte',
        ),
    ]
