# Generated by Django 5.1.6 on 2025-03-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
