# Generated by Django 5.1.6 on 2025-03-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
