# Generated by Django 5.1.6 on 2025-03-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_message_conversation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
