# Generated by Django 5.1.8 on 2025-04-15 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('achat', 'Acheter un bien'), ('vente', 'Vendre un bien')], max_length=10)),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio')], max_length=20)),
                ('nombre_pieces', models.IntegerField(default=1)),
                ('superficie', models.PositiveIntegerField(default=50)),
                ('budget', models.PositiveIntegerField(default=150000)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('exterieur', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('transport', models.CharField(blank=True, choices=[('tram', 'Tram'), ('metro', 'Métro'), ('bus', 'Bus'), ('gare', 'Gare')], max_length=10)),
                ('travaux', models.CharField(blank=True, choices=[('aucun', 'Aucun travaux'), ('petits', 'Petits travaux'), ('renovation', 'Rénovation complète')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
