# Generated by Django 5.1.6 on 2025-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_immobilierparcourscategory_indexpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilierparcourscategory',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, verbose_name="Nom de l'icône"),
        ),
    ]
